services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ps-client
    ports:
      - 5173:5173

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ps-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    restart: always
    environment:
      PORT: :5000

  db:
    image: postgres:16.3
    container_name: ps-postgres
    ports:
      - 5432:5432
    user: postgres
    environment:
      # PGUSER: postgres
      POSTGRES_PASSWORD: pspg
      POSTGRES_DB: scoreboard
      restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 10s
      retries: 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
