services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ps-api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    restart: always
    environment:
      PORT: :5000

  client:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ps-client
    ports:
      - 5173:5173
