services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ps-server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    restart: always
    environment:
      PORT: :5000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ps-client
    ports:
      - 5173:5173
